name: PR check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - closed

permissions:
  pull-requests: write
  contents: write

jobs:
  Audit-the-json-content:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from a fork
        id: pr_source
        run: |
          if [[ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]]; then
            echo "PR is from a fork."
            echo "::set-output name=is_fork::true"
          else
            echo "PR is not from a fork."
            echo "::set-output name=is_fork::false"
          fi

      - name: Checkout the base branch
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0

      - name: Fetch the PR changes from the fork
        if: steps.pr_source.outputs.is_fork == 'true'
        run: |
          # Fetch the pull request branch from the fork repository
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch
          git checkout pr-branch

      - name: Get the PR author username
        id: pr_user
        run: |
          PR_USER=${{ github.event.pull_request.user.login }}
          echo "The PR was created by $PR_USER"
          echo "::set-output name=pr_user::$PR_USER"

      - name: Create a new branch with the PR author username
        id: create_branch
        run: |
          REPO=${{ github.repository }}
          PR_USER=${{ steps.pr_user.outputs.pr_user }}
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}

          # Check if a branch with the username already exists
          BRANCH_NAME=$PR_USER
          COUNT=1
          while git ls-remote --exit-code --heads "https://github.com/${REPO}.git" "refs/heads/$BRANCH_NAME"; do
            COUNT=$((COUNT+1))
            BRANCH_NAME="${PR_USER}${COUNT}"
          done

          # Create a new branch from the base branch
          git checkout $BASE_BRANCH
          git checkout -b "$BRANCH_NAME"

      - name: Merge PR changes into the new branch
        run: |
          git merge --no-ff pr-branch

      - name: Push the new branch to the repository
        run: |
          BRANCH_NAME=${{ steps.create_branch.outputs.branch_name }}
          git push origin "$BRANCH_NAME"
