name: PR check

on:
   pull_request:
      types:
        - opened
        - edited

jobs:
  Audit-Pull-Request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const requiredLabels = ['pixel'];
            let labels = [];

            if (context.payload.pull_request) {
              labels = context.payload.pull_request.labels;
            }

            if (labels.filter(l => requiredLabels.includes(l.name)).length === 0) {
              throw new Error(`Required labels: ${requiredLabels.join(', ')}`);
            }
