name: PR check

on:
    pull_request:
      types:
        - opened
        - edited

jobs:
  Audit-Pull-Request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const requiredLabels = ['pixel'];
            let labels = [];

            if (context.payload.pull_request) {
              labels = context.payload.pull_request.labels;
            }

            if (labels.filter(l => requiredLabels.includes(l.name)).length === 0) {
              throw new Error(`Required labels: ${requiredLabels.join(', ')}`);
            }
  Audit-the-json-content:
    runs-on: ubuntu--latest
    needs: Audit-Pull-Request

    steps:
      - name: checkout the pr 
        uses: actions/checkout@v2

      - name: Show changed files
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }}

      - name: Run Python validation on changed files
        run: |
          # Here we are assuming that the PR contains a JSON file named 'pixel_update.json'
          if git diff --name-only origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }} | grep -q 'pixel_update.json'; then
            echo "pixel_update.json found, validating..."
            python validate_pixel_update.py pixel_update.json
          else
            echo "No pixel_update.json found, skipping validation."
          fi
